version: '3.7'

services:
  app: 
    build: .
    container_name: eventlabs
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links: 
      - db
    depends_on:
      - db
  db:
    image: postgres
    container_name: eventlabs_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eventlabs
networks:
  overlay: